import "./globals.css";
import { Ubuntu } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ScrollTop from "./components/ScrollTop"; // client wrapper

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu",
});

export const metadata = {
  title: "Camera Crew",
  description: "Generated by Md Jahirul Islam Tuku",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ubuntu.variable} font-sans antialiased`}>
        <Navbar />
        <main className="min-h-screen bg-base-200 max-w-7xl mx-auto w-full px-4">
          {children}
        </main>
        <Footer />
        <ScrollTop /> {/* client component */}
      </body>
    </html>
  );
}
