
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="h-screen place-items-center place-content-center bg-base-200 max-w-280 mx-auto w-full">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
